### ISSUE TITLE
UnitType does not work as enum

### ISSUE THREAD

**Issue by pythonmax** [vjurenka/BWMirror#13]
Here http://bwmirror.jurenka.sk/#unitType is stated that each UnitType has single instance.
But simple test gives unexpected result:
Inside onStart() listener:
System.out.println(UnitType.Terran_SCV.whatBuilds().first == UnitType.Terran_Command_Center);
gives me "false", however left and right instance in toString() are indeed "Terran_Command_Center".

Am I missing something?

PS: I'm using latest release version 2.3

**Comment by heinermann** [comment]
All types should be turned into enums in this case, with an integer value specified to be the same value as in BWAPI.

**Comment by vjurenka** [comment]
@pythonmax , Thanks, for the report. 
It's indeed true that these only a single instance for each unit type is created and thus == operator should work. However, there was a bug in the whatBuilds (and about three other, returning a Pair type), which was not returning the correct instance, but creating a new one. 

This bug is fixed in ~~BWAPI~~ BWMirror 2.4, which was just released :)

**Comment by heinermann** [comment]
You mean BWMirror 2.4.
BWAPI 2.4 is deprecated. :P

**Comment by vjurenka** [comment]
Yeah, BWMirror it is :smile:
