### ISSUE TITLE
Error: Client and Server are not compatible! Client Revision: 4625 Server Revision: 4615

### ISSUE THREAD

**Issue by Darker** [vjurenka/BWMirror#3]
Hello, this problem is described in the FAQ but completely wrongly. If you ever tried to download latest release of BWAPI ([4.1.0](https://github.com/bwapi/bwapi/releases/tag/v4.1.0-Beta)) you'd see that in the Chaos launcher, the revision number is 4615, not 4625. There is no release with revision number 4625 on the internet.

**Comment by chriscoxe** [comment]
I can reproduce this issue.  I notice that the [BWAPI GitHub releases web page](https://github.com/bwapi/bwapi/releases) says:

> Note: This was re-released because of the regression addressed in 5af2392.

That might explain it, i.e. BWMirror might have been released after being built with the original release of BWAPI.

**Comment by chriscoxe** [comment]
There have been exactly 10 commits to the master branch of BWAPI since BWAPI 4.1.0 Beta was released (the last commit before the release was on 26 Jan 2015) and 4625 - 4615 is 10 so I think it is more likely that whoever built the BWMirror release built BWAPI from source code rather than using the official BWAPI 4.1.0 Beta release download.  When you build BWAPI from source code it runs command "git rev-list HEAD --count" and adds 2383 to that to set its revision number.  I am not a git expert but maybe this returns the subsequent commits as well, rather than just the commits up to the release.  Maybe it depends how you've set up the project files on your computer with git.

**Comment by vjurenka** [comment]
Hello guys,
please udpate to 2.3 to solve this issue. 
From now on, 4615 will be required until there's another official release of BWAPI>

The story behind it:
I've actually built the BWMIrror API from the **official release** BWAPI 4.1.0 sources.
However, it still pulls the revision number from github.... so there it is.

**Comment by chriscoxe** [comment]
Thanks, it works for me now, i.e. I can now get the example bot that is included in the official BWMirror 2.3 source code release working with BWAPI 4.1.0 Beta.  I added a post in #2 showing how to run the example bot and what the output you should expect to see if it is working.
