### ISSUE TITLE
Always show false on hasCreep(TilePosition) and canBuildHere(TilePosition, UnitType)

### ISSUE THREAD

**Issue by roman-kiselenko** [vjurenka/BWMirror#5]
I use last version BWMirror 2.2
For some reason two methods `hasCreep(TilePosition)` and `canBuildHere(TilePosition, UnitType)` return false for me.
I try to find position with creep or position for build something.
![creep_and_build](https://cloud.githubusercontent.com/assets/3471384/7102069/98a58e4e-e07d-11e4-9174-f0b362b5a08a.png)

BWMirrot 1.2 works good with the same code.
Maybe it is BWAPI bug?

``` java
  TilePosition t = hive.startLocations.get(7); // array with TilePosition 
  game.drawBoxMap(t.getX(), t.getY(), t.getX() + 20, t.getY() + 20, Color.Cyan);
  game.drawTextMap(t.getX(), t.getY(), "Can build? " + game.canBuildHere(t, UnitType.Zerg_Spawning_Pool));
  game.drawTextMap(t.getX(), t.getY(), "Has Creep? " + game.hasCreep(t.getX(), t.getY()));
```

**Comment by vjurenka** [comment]
Hi fishbullet,
I'm pretty sure you are mixing Positions and TilePositions.

Position represents a pixel level coordinate - use these when drawing on the game map.
TilePosition is, well, a tile position where tile is 32x32 square of pixels - use these when calling game.canBuildHere or game.hasCreep.

I'm not sure what this call 

```
           hive.startLocations.get(7);
```

does, but it clearly returns what should be a Position, because when you call game.drawTextMap(t.getX(), t.getY() it appears to be close to the hatchery. (If that would be the hatchery's tile position, the rectangle would be much closer to the upper left corner of the map)

Here is a simple test case to show the correct calls

```
            for (Unit myUnit : self.getUnits()) {
                if (myUnit.getType() == UnitType.Zerg_Hatchery) {
                    Position p = myUnit.getPosition();
                    TilePosition t = myUnit.getTilePosition();

                    game.drawBoxMap(p.getX(), p.getY(), p.getX() + 20, p.getY() + 20, Color.Cyan);
                    game.drawTextMap(p.getX(), p.getY(), "Can build? " + game.canBuildHere(t, UnitType.Zerg_Spawning_Pool) + "\nHas Creep? " + game.hasCreep(t.getX(), t.getY()));
                }
            }
```

![image](https://cloud.githubusercontent.com/assets/6848914/7102593/f4ac205c-e084-11e4-8192-77130d3f5e7a.png)

Here's another test case, where canBuild returns true (we offset the Hatchery's position by 3 tiles on both axes)

```
            for (Unit myUnit : self.getUnits()) {
                if (myUnit.getType() == UnitType.Zerg_Hatchery) {
                    TilePosition origin = myUnit.getTilePosition();

                    TilePosition t = new TilePosition(origin.getX() + 3, origin.getY() + 3); //offset to get a tile postion
                    Position p = new Position(t.getX() * 32, t.getY() * 32); //this conversion is so ugly :(, I should add a helper method 


                    game.drawBoxMap(p.getX(), p.getY(), p.getX() + 20, p.getY() + 20, Color.Cyan);
                    game.drawTextMap(p.getX(), p.getY(), "Can build? " + game.canBuildHere(t, UnitType.Zerg_Spawning_Pool) + "\nHas Creep? " + game.hasCreep(t.getX(), t.getY()));
                }
            }
```

![image](https://cloud.githubusercontent.com/assets/6848914/7102592/e5f30080-e084-11e4-9948-6aaaa099b8b0.png)

Let me know if that works for you :)

**Comment by roman-kiselenko** [comment]
@vjurenka  thanks for quick response. Looks like i did not understand the documentation. I try to test it today.

**Comment by roman-kiselenko** [comment]
yep, my problem in mixing TilePosition and Position. Thanks for the good explain  @vjurenka.
![fooaw](https://cloud.githubusercontent.com/assets/3471384/7142634/a8403a5e-e2e2-11e4-8330-3ffdbb446a0e.png)
